- platform: template
  sensors:
    low_battery_level:
      unique_id: "1234567890106"
      friendly_name: "Low battery"
      value_template: >
        {{  states.sensor 
          | selectattr('attributes.device_class', 'defined') 
          | rejectattr('state', 'in', ['unavailable', 'unknown', 'none']) 
          | selectattr('attributes.device_class', 'eq', 'battery') 
          | map(attribute='state') | map('int') 
          | select("lessthan", 11) | list | count > 0
        }}
      icon_template: mdi:battery-low
